name: Daily cron

on:
  schedule:
    # run every day at 3am UTC
    - cron: '0 3 * * *'
  pull_request:
    # We also want this workflow triggered if the 'Extra CI' label is added
    # or present when PR is updated
    types:
      - synchronize
      - labeled

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "true"

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    if: (github.repository == 'astropy/astropy' && (github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'Extra CI')))
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: Bundling with pyinstaller
            os: ubuntu-latest
            python: 3.8
            toxenv: pyinstaller

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install language-pack-de and tzdata
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install language-pack-de tzdata
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox
    - name: Run tests
      run: tox ${{ matrix.toxargs}} -e ${{ matrix.toxenv}} -- ${{ matrix.toxposargs}}

  # TODO: Remove debug-only when ready for production.
  # NOTE: remove-pr-stale-when-updated includes comments/milestones, resulting in false negative.
  stalebot:
    runs-on: ubuntu-latest
    if: github.repository == 'astropy/astropy' && github.event_name == 'schedule'
    steps:
    - uses: actions/stale@v3
      with:
        debug-only: true

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        operations-per-run: 50
        ascending: false

        days-before-issue-stale: -1
        days-before-issue-close: 7
        remove-issue-stale-when-updated: false
        close-issue-message: 'I am going to close this issue because it was marked with **Close?**, but if you feel that this issue should stay open, then feel free to re-open, remove **Close?** and **closed-by-bot** labels, and apply **keep-open** label.'
        stale-issue-label: 'Close?'
        close-issue-label: 'closed-by-bot'
        exempt-issue-labels: 'keep-open'
        any-of-issue-labels: 'Close?'

        days-before-pr-stale: 150
        days-before-pr-close: 30
        remove-pr-stale-when-updated: false
        stale-pr-message: 'This pull request is stale because it has been open 150 days with no activity. Remove **Close?** or this will be closed in 30 days. Apply **keep-open** if you want to keep it open indefinitely.'
        close-pr-message: 'I am going to close this pull request as per my previous message, but if you feel that this PR should stay open, then feel free to re-open, remove **Close?** and **closed-by-bot** labels, and apply **keep-open** label.'
        stale-pr-label: 'Close?'
        close-pr-label: 'closed-by-bot'
        exempt-pr-labels: 'keep-open'
